### ISSUE TITLE
Data Iterator not working in Lumira 2.0

### ISSUE THREAD

**Issue by ShivaShankarGangala** [org-scn-design-studio-community/lumiradesignercommunityext#18]
Hi All,

Please help me on the below issue.
Recently we have upgrade from SAP Design Studio 1.6 SP5 to SAP Lumira 2.0 and when i verify i am getting error in one of the Dashboard.Rest all of the reports are working fine.Getting strange error Script error.

Below the error
Error during script processing. Contact the Application Designer to resolve the issue.
When i open the Dashboard and see any script errors i dont see any errors

Same dashboard when i open it in Design Studio 1.6 SP5 i am not getting any error.

Raised incident with SAP on this issue.They have suggested to upgrade to SAP Lumira SP03.I have done but still getting the same error.
Can anyone help on the issue?

Thanks

Shiva Shankar

**Comment by ShivaShankarGangala** [comment]
Adding to the Point

1. We have used Bookmarks to the Dashboard.
2.Added SDK from below link

https://github.com/org-scn-design-studio-community/lumiradesignercommunityext/blob/master/releases/org.scn.community.sdk.extensions.zip?raw=true

Just want to check am i missing anything apart from this SDK's?

**Comment by ShivaShankarGangala** [comment]
Below the error
![image](https://user-images.githubusercontent.com/33743074/32937613-351bad3e-cbb4-11e7-806c-1e7c814a2ddc.png)

**Comment by ShivaShankarGangala** [comment]
Error 
![image](https://user-images.githubusercontent.com/33743074/32937668-6d292076-cbb4-11e7-9737-2162ca86747f.png)

**Comment by ShivaShankarGangala** [comment]
Hi Mike,

Came to know DATA Iterator SDK is not working properly .its throwing error in Lumira 2.0a dn came to know this is because of **Dataiterator SDK component**

Below is the error message
!ENTRY com.sap.ip.bi.base.application 4 0 2017-11-22 17:48:17.980
!MESSAGE Message: org.mozilla.javascript.EcmaError: ReferenceError: "createDataRowArray" is not defined. (DATAITERATOR_MAXDMD.getRows()#6)
Stack trace: com.sap.ip.bi.zen.rt.framework.jsengine.JsEngineException: org.mozilla.javascript.EcmaError: ReferenceError: "createDataRowArray" is not defined. (DATAITERATOR_MAXDMD.getRows()#6)
at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoJsEngine.handleError(RhinoJsEngine.java:194)
at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoJsEngine.doRunScript(RhinoJsEngine.java:88)
at com.sap.ip.bi.zen.rt.framework.jsengine.AbstractJsEngine.runScript(AbstractJsEngine.java:12)

Can you please help on fixing this.Thanks

**Comment by VikasSinghThakur** [comment]
Hi ShivaShankar,

Have you find any solution for Data Iterator in Lumira 2.0
