### ISSUE TITLE
Data Iterator not working in Lumira 2.0

### ISSUE THREAD

**Issue by mosamna** [org-scn-design-studio-community/lumiradesignercommunityext#8]
**# Data Iterator not working in Lumira 2.0**
**Session Data:**
"eclipse.buildId=@qualifier@
java.version=1.8.0_131
java.vendor=SAP AG
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  BusinessObjects Lumira Designer
Command-line arguments:  -os win32 -ws win32 -arch x86_64 BusinessObjects Lumira Designer"

**below is the call stack of the error:**

org.mozilla.javascript.EcmaError: ReferenceError: "createDataRowArray" is not defined. (VE_DATAITERATOR.getRows()#6)
	at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoJsEngine.handleError(RhinoJsEngine.java:194)
	at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoJsEngine.doResumeScript(RhinoJsEngine.java:172)
	at com.sap.ip.bi.zen.rt.framework.jsengine.AbstractJsEngine.resumeScript(AbstractJsEngine.java:25)
	at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoJsEngine.runScriptWithErrorLogging(RhinoJsEngine.java:108)
	at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoScriptInterpreterBialService.runScript(RhinoScriptInterpreterBialService.java:182)
	at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoScriptInterpreterBialService.interprete(RhinoScriptInterpreterBialService.java:136)
	at com.sap.ip.bi.base.command.impl.Command.interprete(Command.java:191)
	at com.sap.ip.bi.webapplications.runtime.impl.page.Page.processScriptCommand(Page.java:4067)
	at com.sap.ip.bi.webapplications.runtime.impl.page.Page.processCommandSequence(Page.java:3872)
	at com.sap.ip.bi.webapplications.runtime.impl.page.Page.doProcessRequest(Page.java:2105)
	at com.sap.ip.bi.webapplications.runtime.impl.page.Page._processRequest(Page.java:670)
	at com.sap.ip.bi.webapplications.runtime.impl.page.Page.processRequest(Page.java:4332)
	at com.sap.ip.bi.webapplications.runtime.impl.page.Page.processRequest(Page.java:4324)
	at com.sap.ip.bi.webapplications.runtime.impl.controller.Controller.doProcessRequest(Controller.java:1241)
	at com.sap.ip.bi.webapplications.runtime.impl.controller.Controller._processRequest(Controller.java:1095)
	at com.sap.ip.bi.webapplications.runtime.impl.controller.Controller.processRequest(Controller.java:1061)
	at com.sap.ip.bi.webapplications.runtime.impl.controller.Controller.processRequest(Controller.java:1)
	at com.sap.ip.bi.server.runtime.sevice.impl.BIRuntimeServerService._handleRequest(BIRuntimeServerService.java:519)
	at com.sap.ip.bi.server.runtime.sevice.impl.BIRuntimeServerService.handleRequest(BIRuntimeServerService.java:967)
	at com.sap.ip.bi.server.execution.engine.runtime.LocalBIExecutionService.executeRequest(LocalBIExecutionService.java:34)
	at com.sap.ip.bi.zen.rt.client.handler.designer.LocalExecutionAdapter.executeRequest(LocalExecutionAdapter.java:39)
	at com.sap.ip.bi.zen.rt.client.handler.RuntimeRequestHandler.handleRequest(RuntimeRequestHandler.java:28)
	at com.sap.ip.bi.zen.rt.client.handler.designer.DesignerRuntimeRequestHandler.handleRequest(DesignerRuntimeRequestHandler.java:33)
	at com.sap.ip.bi.zen.rt.client.handler.MainHandler.executeBiRequest(MainHandler.java:69)
	at com.sap.ip.bi.zen.rt.client.handler.MainHandler.handleRegularRequest(MainHandler.java:57)
	at com.sap.ip.bi.zen.rt.client.handler.MainHandler.handleRequest(MainHandler.java:35)
	at com.sap.ip.bi.zen.rt.client.handler.PathHandler.handleRequest(PathHandler.java:54)
	at com.sap.ip.bi.zen.rt.client.handler.designer.DesignerPathHandler.handleRequest(DesignerPathHandler.java:56)
	at com.sap.ip.bi.zen.rt.client.handler.AbstractSupportabilityHandler.handleRequest(AbstractSupportabilityHandler.java:25)
	at com.sap.ip.bi.zen.rt.client.handler.AbstractFrontServlet.handleRequest(AbstractFrontServlet.java:73)
	at com.sap.ip.bi.zen.rt.client.handler.AbstractFrontServlet.handleRequest(AbstractFrontServlet.java:29)
	at com.sap.ip.bi.zen.rt.client.handler.AbstractFrontServlet.doPost(AbstractFrontServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at com.sap.ip.bi.zen.rt.client.handler.AbstractFrontServlet.service(AbstractFrontServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1232)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
	at com.sap.ip.bi.zen.webserver.designer.ZenSessionFilter.doFilter(ZenSessionFilter.java:57)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyFilterFactory$LegacyFilter.doFilter(HttpServiceRuntimeImpl.java:1191)
	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:118)
	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:71)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:98)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl.doDispatch(HttpServiceRuntimeImpl.java:372)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:357)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:808)
Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "createDataRowArray" is not defined. (VE_DATAITERATOR.getRows()#6)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3750)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1794)
	at org.mozilla.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2188)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1308)
	at org.mozilla.javascript.Interpreter.restartContinuation(Interpreter.java:875)
	at org.mozilla.javascript.NativeContinuation.call(NativeContinuation.java:48)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.CustomContextFactory.doTopCall(CustomContextFactory.java:77)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.Interpreter.restartContinuation(Interpreter.java:856)
	at org.mozilla.javascript.Context.resumeContinuation(Context.java:1214)
	at com.sap.ip.bi.zen.rt.framework.jsengine.rhino.RhinoJsEngine.doResumeScript(RhinoJsEngine.java:162)
	... 62 more
"

**Comment by entmike** [comment]
Hm I thought I fixed this one. I will look again.

**Comment by mosamna** [comment]
Do I need to delete the old extension installation from Lumira? then install this updated version?

**Comment by entmike** [comment]
Just pushed an update.  This should be finally fixed now, too.  Sorry about delay.

**Comment by mosamna** [comment]
Thank you. It is ok, will test and get back to you to close the issue.

**Comment by entmike** [comment]
Hi, can we close this one?

**Comment by mosamna** [comment]
Hi,
Yeah It seems it is working fine for now. I will not know for sure until fully testing BOYData component along with it. I will close for now.
